import { Candidate, ActivityItem, PipelineStage } from './types';

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();

export const mockCandidates: Candidate[] = [
  {
    id: '1',
    name: 'Sarah Al-Rashid',
    email: 'sarah.rashid@email.com',
    phone: '+966 55 123 4567',
    stage: 'onboarding',
    cvFileName: 'Sarah_AlRashid_CV.pdf',
    uploadedAt: daysAgo(21),
    position: 'Senior Frontend Developer',
    notes: [{ id: 'n1', author: 'HR Team', content: 'Excellent cultural fit. Strong React portfolio.', createdAt: daysAgo(18) }],
    transitions: [
      { from: 'cv_received', to: 'ai_analysis', date: daysAgo(21), by: 'System' },
      { from: 'ai_analysis', to: 'screening', date: daysAgo(20), by: 'System' },
      { from: 'screening', to: 'interview', date: daysAgo(17), by: 'HR Team' },
      { from: 'interview', to: 'ceo_interview', date: daysAgo(14), by: 'HR Team' },
      { from: 'ceo_interview', to: 'technical_task', date: daysAgo(11), by: 'CEO' },
      { from: 'technical_task', to: 'offer_sent', date: daysAgo(7), by: 'HR Team' },
      { from: 'offer_sent', to: 'offer_accepted', date: daysAgo(4), by: 'Candidate' },
      { from: 'offer_accepted', to: 'onboarding', date: daysAgo(1), by: 'HR Team' },
    ],
    aiReport: {
      overallScore: 92,
      summary: 'Exceptional frontend developer with 7+ years of experience in React, TypeScript, and modern web technologies. Strong portfolio demonstrating complex UI implementations. Leadership experience managing teams of 5+. Excellent communication skills evidenced by tech blog and conference talks.',
      skills: [
        { name: 'React / Next.js', level: 'expert', score: 95, yearsOfExperience: 6 },
        { name: 'TypeScript', level: 'expert', score: 92, yearsOfExperience: 5 },
        { name: 'CSS / Tailwind', level: 'expert', score: 90, yearsOfExperience: 7 },
        { name: 'Node.js', level: 'advanced', score: 78, yearsOfExperience: 4 },
        { name: 'System Design', level: 'advanced', score: 82, yearsOfExperience: 3 },
        { name: 'Team Leadership', level: 'advanced', score: 85, yearsOfExperience: 3 },
      ],
      experience: [
        { company: 'TechCorp Saudi', role: 'Senior Frontend Developer', startDate: '2021', endDate: 'Present', description: 'Led frontend architecture for fintech platform serving 2M+ users.' },
        { company: 'Digital Solutions LLC', role: 'Frontend Developer', startDate: '2018', endDate: '2021', description: 'Built responsive web applications for e-commerce clients.' },
        { company: 'StartupHub', role: 'Junior Developer', startDate: '2016', endDate: '2018', description: 'Full-stack development on early-stage products.' },
      ],
      education: [
        { institution: 'King Saud University', degree: 'BSc', field: 'Computer Science', year: '2016' },
      ],
      strengths: ['Deep React ecosystem expertise', 'Strong system design thinking', 'Proven leadership and mentoring ability', 'Active open-source contributor'],
      concerns: ['Limited backend/infrastructure experience', 'May require adjustment to smaller team dynamics'],
      recommendedStage: 'screening',
      analyzedAt: daysAgo(20),
    },
  },
  {
    id: '2',
    name: 'Omar Khalil',
    email: 'omar.khalil@email.com',
    phone: '+966 50 987 6543',
    stage: 'technical_task',
    cvFileName: 'Omar_Khalil_Resume.pdf',
    uploadedAt: daysAgo(14),
    position: 'Backend Engineer',
    notes: [{ id: 'n2', author: 'CTO', content: 'Strong distributed systems background. Schedule technical assessment.', createdAt: daysAgo(10) }],
    transitions: [
      { from: 'cv_received', to: 'ai_analysis', date: daysAgo(14), by: 'System' },
      { from: 'ai_analysis', to: 'screening', date: daysAgo(13), by: 'System' },
      { from: 'screening', to: 'interview', date: daysAgo(11), by: 'HR Team' },
      { from: 'interview', to: 'ceo_interview', date: daysAgo(8), by: 'HR Team' },
      { from: 'ceo_interview', to: 'technical_task', date: daysAgo(5), by: 'CEO' },
    ],
    aiReport: {
      overallScore: 87,
      summary: 'Highly skilled backend engineer with expertise in Python, Go, and distributed systems. 5 years of experience building scalable microservices architectures. Strong understanding of cloud infrastructure and DevOps practices.',
      skills: [
        { name: 'Python', level: 'expert', score: 94, yearsOfExperience: 5 },
        { name: 'Go', level: 'advanced', score: 82, yearsOfExperience: 3 },
        { name: 'PostgreSQL', level: 'expert', score: 90, yearsOfExperience: 5 },
        { name: 'Docker / K8s', level: 'advanced', score: 85, yearsOfExperience: 4 },
        { name: 'System Design', level: 'advanced', score: 88, yearsOfExperience: 4 },
        { name: 'AWS', level: 'advanced', score: 80, yearsOfExperience: 4 },
      ],
      experience: [
        { company: 'CloudScale Inc', role: 'Senior Backend Engineer', startDate: '2020', endDate: 'Present', description: 'Architected microservices handling 10K+ RPS.' },
        { company: 'DataFlow Systems', role: 'Backend Developer', startDate: '2018', endDate: '2020', description: 'Built real-time data processing pipelines.' },
      ],
      education: [
        { institution: 'KAUST', degree: 'MSc', field: 'Computer Science', year: '2018' },
        { institution: 'King Fahd University', degree: 'BSc', field: 'Software Engineering', year: '2016' },
      ],
      strengths: ['Expert in distributed systems', 'Strong database optimization skills', 'Cloud-native architecture experience', 'Published research in data processing'],
      concerns: ['Limited frontend exposure', 'Prefers individual work over team collaboration'],
      recommendedStage: 'screening',
      analyzedAt: daysAgo(13),
    },
  },
  {
    id: '3',
    name: 'Fatima Hassan',
    email: 'fatima.h@email.com',
    stage: 'interview',
    cvFileName: 'Fatima_Hassan_CV.pdf',
    uploadedAt: daysAgo(10),
    position: 'UI/UX Designer',
    notes: [],
    transitions: [
      { from: 'cv_received', to: 'ai_analysis', date: daysAgo(10), by: 'System' },
      { from: 'ai_analysis', to: 'screening', date: daysAgo(9), by: 'System' },
      { from: 'screening', to: 'interview', date: daysAgo(6), by: 'HR Team' },
    ],
    aiReport: {
      overallScore: 79,
      summary: 'Creative UI/UX designer with 4 years of experience in mobile and web design. Strong Figma skills and solid understanding of design systems. Portfolio shows clean, user-centered design approach.',
      skills: [
        { name: 'Figma', level: 'expert', score: 95, yearsOfExperience: 4 },
        { name: 'UI Design', level: 'advanced', score: 85, yearsOfExperience: 4 },
        { name: 'UX Research', level: 'intermediate', score: 68, yearsOfExperience: 2 },
        { name: 'Prototyping', level: 'advanced', score: 80, yearsOfExperience: 3 },
        { name: 'Design Systems', level: 'advanced', score: 78, yearsOfExperience: 3 },
      ],
      experience: [
        { company: 'DesignLab Riyadh', role: 'Senior UI Designer', startDate: '2022', endDate: 'Present', description: 'Lead designer for enterprise SaaS products.' },
        { company: 'Creative Agency', role: 'UI/UX Designer', startDate: '2020', endDate: '2022', description: 'Designed mobile apps and marketing websites.' },
      ],
      education: [
        { institution: 'Princess Nourah University', degree: 'BA', field: 'Visual Communication', year: '2020' },
      ],
      strengths: ['Exceptional visual design skills', 'Strong design system knowledge', 'Good collaboration with developers'],
      concerns: ['Limited UX research methodology experience', 'No experience with AR/VR design'],
      recommendedStage: 'screening',
      analyzedAt: daysAgo(9),
    },
  },
  {
    id: '4',
    name: 'Ahmed bin Nasser',
    email: 'ahmed.nasser@email.com',
    stage: 'ceo_interview',
    cvFileName: 'Ahmed_Nasser_Resume.pdf',
    uploadedAt: daysAgo(12),
    position: 'DevOps Engineer',
    notes: [{ id: 'n4', author: 'CTO', content: 'Impressive Kubernetes expertise. Fast-track to CEO interview.', createdAt: daysAgo(8) }],
    transitions: [
      { from: 'cv_received', to: 'ai_analysis', date: daysAgo(12), by: 'System' },
      { from: 'ai_analysis', to: 'screening', date: daysAgo(11), by: 'System' },
      { from: 'screening', to: 'interview', date: daysAgo(9), by: 'HR Team' },
      { from: 'interview', to: 'ceo_interview', date: daysAgo(5), by: 'HR Team' },
    ],
    aiReport: {
      overallScore: 84,
      summary: 'Experienced DevOps engineer with strong Kubernetes and CI/CD pipeline expertise. 6 years in cloud infrastructure management. Certified AWS Solutions Architect.',
      skills: [
        { name: 'Kubernetes', level: 'expert', score: 93, yearsOfExperience: 4 },
        { name: 'Terraform', level: 'advanced', score: 85, yearsOfExperience: 3 },
        { name: 'AWS', level: 'expert', score: 90, yearsOfExperience: 6 },
        { name: 'CI/CD', level: 'expert', score: 92, yearsOfExperience: 5 },
        { name: 'Linux', level: 'advanced', score: 88, yearsOfExperience: 6 },
        { name: 'Python', level: 'intermediate', score: 65, yearsOfExperience: 3 },
      ],
      experience: [
        { company: 'MegaCloud KSA', role: 'Senior DevOps Engineer', startDate: '2021', endDate: 'Present', description: 'Managed multi-region K8s clusters for banking platform.' },
        { company: 'InfraTech', role: 'DevOps Engineer', startDate: '2018', endDate: '2021', description: 'Built CI/CD pipelines and automated infrastructure provisioning.' },
      ],
      education: [
        { institution: 'King Abdulaziz University', degree: 'BSc', field: 'Information Technology', year: '2018' },
      ],
      strengths: ['Deep Kubernetes expertise', 'AWS certified', 'Strong automation mindset', 'Excellent incident response'],
      concerns: ['Limited application development background', 'Could improve documentation practices'],
      recommendedStage: 'screening',
      analyzedAt: daysAgo(11),
    },
  },
  {
    id: '5',
    name: 'Layla Mohammed',
    email: 'layla.m@email.com',
    stage: 'screening',
    cvFileName: 'Layla_Mohammed_CV.pdf',
    uploadedAt: daysAgo(5),
    position: 'Product Manager',
    notes: [],
    transitions: [
      { from: 'cv_received', to: 'ai_analysis', date: daysAgo(5), by: 'System' },
      { from: 'ai_analysis', to: 'screening', date: daysAgo(4), by: 'System' },
    ],
    aiReport: {
      overallScore: 76,
      summary: 'Product manager with 3 years of experience in agile environments. Good understanding of user research and product analytics. Previous background in engineering adds technical depth.',
      skills: [
        { name: 'Product Strategy', level: 'advanced', score: 80, yearsOfExperience: 3 },
        { name: 'Agile / Scrum', level: 'advanced', score: 85, yearsOfExperience: 3 },
        { name: 'User Research', level: 'intermediate', score: 70, yearsOfExperience: 2 },
        { name: 'Data Analytics', level: 'intermediate', score: 68, yearsOfExperience: 2 },
        { name: 'Technical Writing', level: 'advanced', score: 75, yearsOfExperience: 3 },
      ],
      experience: [
        { company: 'ProductFirst', role: 'Product Manager', startDate: '2022', endDate: 'Present', description: 'Managed product roadmap for B2B SaaS platform.' },
        { company: 'TechStartup', role: 'Associate PM', startDate: '2021', endDate: '2022', description: 'Coordinated sprint planning and stakeholder communications.' },
      ],
      education: [
        { institution: 'Effat University', degree: 'BSc', field: 'Computer Engineering', year: '2020' },
      ],
      strengths: ['Strong technical background', 'Excellent stakeholder communication', 'Data-driven decision making'],
      concerns: ['Relatively junior for senior PM role', 'Limited B2C product experience'],
      recommendedStage: 'screening',
      analyzedAt: daysAgo(4),
    },
  },
  {
    id: '6',
    name: 'Khalid Al-Dosari',
    email: 'khalid.dosari@email.com',
    stage: 'ai_analysis',
    cvFileName: 'Khalid_AlDosari_Resume.pdf',
    uploadedAt: daysAgo(1),
    position: 'Full Stack Developer',
    notes: [],
    transitions: [
      { from: 'cv_received', to: 'ai_analysis', date: daysAgo(1), by: 'System' },
    ],
    aiReport: {
      overallScore: 71,
      summary: 'Full-stack developer with solid fundamentals in React and Node.js. 3 years of experience building web applications. Shows growth potential with active GitHub profile.',
      skills: [
        { name: 'React', level: 'intermediate', score: 72, yearsOfExperience: 3 },
        { name: 'Node.js', level: 'intermediate', score: 70, yearsOfExperience: 3 },
        { name: 'MongoDB', level: 'intermediate', score: 65, yearsOfExperience: 2 },
        { name: 'TypeScript', level: 'intermediate', score: 68, yearsOfExperience: 2 },
        { name: 'Git', level: 'advanced', score: 80, yearsOfExperience: 3 },
      ],
      experience: [
        { company: 'WebDev Studio', role: 'Full Stack Developer', startDate: '2022', endDate: 'Present', description: 'Built custom web solutions for SME clients.' },
        { company: 'Freelance', role: 'Web Developer', startDate: '2021', endDate: '2022', description: 'Freelance web development projects.' },
      ],
      education: [
        { institution: 'Imam University', degree: 'BSc', field: 'Computer Science', year: '2021' },
      ],
      strengths: ['Solid JavaScript fundamentals', 'Active learner', 'Good GitHub portfolio'],
      concerns: ['Limited enterprise experience', 'No experience with large-scale systems', 'Relatively junior'],
      recommendedStage: 'screening',
      analyzedAt: hoursAgo(6),
    },
  },
  {
    id: '7',
    name: 'Nora Al-Qahtani',
    email: 'nora.q@email.com',
    stage: 'cv_received',
    cvFileName: 'Nora_AlQahtani_CV.pdf',
    uploadedAt: hoursAgo(3),
    position: 'Data Scientist',
    notes: [],
    transitions: [],
  },
  {
    id: '8',
    name: 'Youssef Ibrahim',
    email: 'youssef.i@email.com',
    stage: 'offer_sent',
    cvFileName: 'Youssef_Ibrahim_CV.pdf',
    uploadedAt: daysAgo(18),
    position: 'Cloud Architect',
    notes: [{ id: 'n8', author: 'HR Team', content: 'Offer sent with competitive package. Awaiting response.', createdAt: daysAgo(3) }],
    transitions: [
      { from: 'cv_received', to: 'ai_analysis', date: daysAgo(18), by: 'System' },
      { from: 'ai_analysis', to: 'screening', date: daysAgo(17), by: 'System' },
      { from: 'screening', to: 'interview', date: daysAgo(15), by: 'HR Team' },
      { from: 'interview', to: 'ceo_interview', date: daysAgo(12), by: 'HR Team' },
      { from: 'ceo_interview', to: 'technical_task', date: daysAgo(9), by: 'CEO' },
      { from: 'technical_task', to: 'offer_sent', date: daysAgo(3), by: 'HR Team' },
    ],
    aiReport: {
      overallScore: 91,
      summary: 'Exceptional cloud architect with 8 years of experience across AWS, GCP, and Azure. Led cloud migration projects for Fortune 500 companies. Deep expertise in serverless and multi-cloud strategies.',
      skills: [
        { name: 'AWS', level: 'expert', score: 96, yearsOfExperience: 8 },
        { name: 'GCP', level: 'advanced', score: 82, yearsOfExperience: 4 },
        { name: 'Terraform', level: 'expert', score: 90, yearsOfExperience: 5 },
        { name: 'Serverless', level: 'expert', score: 88, yearsOfExperience: 4 },
        { name: 'Security', level: 'advanced', score: 85, yearsOfExperience: 6 },
        { name: 'Cost Optimization', level: 'expert', score: 92, yearsOfExperience: 5 },
      ],
      experience: [
        { company: 'Enterprise Cloud Co', role: 'Principal Cloud Architect', startDate: '2020', endDate: 'Present', description: 'Led multi-cloud strategy for regional banking group.' },
        { company: 'CloudFirst MENA', role: 'Senior Cloud Engineer', startDate: '2017', endDate: '2020', description: 'Architected cloud solutions for government sector.' },
      ],
      education: [
        { institution: 'KFUPM', degree: 'MSc', field: 'Computer Engineering', year: '2017' },
        { institution: 'KFUPM', degree: 'BSc', field: 'Computer Engineering', year: '2015' },
      ],
      strengths: ['Multi-cloud expertise', 'Enterprise architecture experience', 'Security-first mindset', 'Cost optimization track record'],
      concerns: ['High salary expectations', 'May be overqualified for current team size'],
      recommendedStage: 'screening',
      analyzedAt: daysAgo(17),
    },
  },
  {
    id: '9',
    name: 'Aisha Malik',
    email: 'aisha.malik@email.com',
    stage: 'offer_accepted',
    cvFileName: 'Aisha_Malik_Resume.pdf',
    uploadedAt: daysAgo(25),
    position: 'QA Engineer',
    notes: [{ id: 'n9', author: 'HR Team', content: 'Accepted! Starting date: March 15.', createdAt: daysAgo(2) }],
    transitions: [
      { from: 'cv_received', to: 'ai_analysis', date: daysAgo(25), by: 'System' },
      { from: 'ai_analysis', to: 'screening', date: daysAgo(24), by: 'System' },
      { from: 'screening', to: 'interview', date: daysAgo(20), by: 'HR Team' },
      { from: 'interview', to: 'ceo_interview', date: daysAgo(16), by: 'HR Team' },
      { from: 'ceo_interview', to: 'technical_task', date: daysAgo(12), by: 'CEO' },
      { from: 'technical_task', to: 'offer_sent', date: daysAgo(6), by: 'HR Team' },
      { from: 'offer_sent', to: 'offer_accepted', date: daysAgo(2), by: 'Candidate' },
    ],
    aiReport: {
      overallScore: 83,
      summary: 'Skilled QA engineer with strong automation testing background. 5 years of experience in both manual and automated testing. Expertise in Selenium, Cypress, and API testing.',
      skills: [
        { name: 'Test Automation', level: 'expert', score: 90, yearsOfExperience: 4 },
        { name: 'Cypress', level: 'expert', score: 88, yearsOfExperience: 3 },
        { name: 'API Testing', level: 'advanced', score: 82, yearsOfExperience: 4 },
        { name: 'CI/CD', level: 'intermediate', score: 72, yearsOfExperience: 2 },
        { name: 'Performance Testing', level: 'intermediate', score: 70, yearsOfExperience: 2 },
      ],
      experience: [
        { company: 'QualityTech', role: 'Senior QA Engineer', startDate: '2021', endDate: 'Present', description: 'Led QA automation for enterprise platform.' },
        { company: 'SoftTest LLC', role: 'QA Engineer', startDate: '2019', endDate: '2021', description: 'Built automated test suites for web applications.' },
      ],
      education: [
        { institution: 'University of Jeddah', degree: 'BSc', field: 'Information Systems', year: '2019' },
      ],
      strengths: ['Strong automation skills', 'Methodical approach to testing', 'Good CI/CD integration knowledge'],
      concerns: ['Limited security testing experience', 'No mobile testing background'],
      recommendedStage: 'screening',
      analyzedAt: daysAgo(24),
    },
  },
  {
    id: '10',
    name: 'Mohammed Al-Harbi',
    email: 'mohammed.h@email.com',
    stage: 'screening',
    cvFileName: 'Mohammed_AlHarbi_CV.pdf',
    uploadedAt: daysAgo(4),
    position: 'Mobile Developer',
    notes: [],
    transitions: [
      { from: 'cv_received', to: 'ai_analysis', date: daysAgo(4), by: 'System' },
      { from: 'ai_analysis', to: 'screening', date: daysAgo(3), by: 'System' },
    ],
    aiReport: {
      overallScore: 74,
      summary: 'Mobile developer with 3 years of experience in React Native and Flutter. Good understanding of mobile-first design principles. Active contributor to mobile development community.',
      skills: [
        { name: 'React Native', level: 'advanced', score: 80, yearsOfExperience: 3 },
        { name: 'Flutter', level: 'intermediate', score: 72, yearsOfExperience: 2 },
        { name: 'iOS / Swift', level: 'intermediate', score: 65, yearsOfExperience: 1 },
        { name: 'Firebase', level: 'advanced', score: 78, yearsOfExperience: 3 },
        { name: 'UI/UX', level: 'intermediate', score: 70, yearsOfExperience: 2 },
      ],
      experience: [
        { company: 'AppFactory', role: 'Mobile Developer', startDate: '2021', endDate: 'Present', description: 'Built cross-platform mobile apps with 100K+ downloads.' },
        { company: 'MobiTech', role: 'Junior Mobile Developer', startDate: '2020', endDate: '2021', description: 'Developed mobile features for e-commerce app.' },
      ],
      education: [
        { institution: 'Taibah University', degree: 'BSc', field: 'Computer Science', year: '2020' },
      ],
      strengths: ['Cross-platform expertise', 'User-focused development', 'Active community contributor'],
      concerns: ['No native iOS/Android depth', 'Limited enterprise mobile experience'],
      recommendedStage: 'screening',
      analyzedAt: daysAgo(3),
    },
  },
  {
    id: '11',
    name: 'Reem Abdullah',
    email: 'reem.a@email.com',
    stage: 'cv_received',
    cvFileName: 'Reem_Abdullah_Resume.pdf',
    uploadedAt: hoursAgo(1),
    position: 'Full Stack Developer',
    notes: [],
    transitions: [],
  },
  {
    id: '12',
    name: 'Tariq Mansour',
    email: 'tariq.m@email.com',
    stage: 'interview',
    cvFileName: 'Tariq_Mansour_CV.pdf',
    uploadedAt: daysAgo(8),
    position: 'Backend Engineer',
    notes: [],
    transitions: [
      { from: 'cv_received', to: 'ai_analysis', date: daysAgo(8), by: 'System' },
      { from: 'ai_analysis', to: 'screening', date: daysAgo(7), by: 'System' },
      { from: 'screening', to: 'interview', date: daysAgo(4), by: 'HR Team' },
    ],
    aiReport: {
      overallScore: 68,
      summary: 'Backend developer with 2 years of experience in Java and Spring Boot. Solid understanding of REST APIs and database design. Growing into microservices architecture.',
      skills: [
        { name: 'Java', level: 'intermediate', score: 72, yearsOfExperience: 2 },
        { name: 'Spring Boot', level: 'intermediate', score: 70, yearsOfExperience: 2 },
        { name: 'MySQL', level: 'intermediate', score: 68, yearsOfExperience: 2 },
        { name: 'REST APIs', level: 'advanced', score: 78, yearsOfExperience: 2 },
        { name: 'Docker', level: 'beginner', score: 45, yearsOfExperience: 1 },
      ],
      experience: [
        { company: 'DevHouse', role: 'Backend Developer', startDate: '2022', endDate: 'Present', description: 'Developed REST APIs for logistics management system.' },
        { company: 'CodeCamp', role: 'Intern', startDate: '2021', endDate: '2022', description: 'Backend development internship.' },
      ],
      education: [
        { institution: 'Qassim University', degree: 'BSc', field: 'Computer Science', year: '2021' },
      ],
      strengths: ['Strong Java fundamentals', 'Quick learner', 'Good API design'],
      concerns: ['Junior level for senior role', 'Limited DevOps knowledge', 'No production-scale experience'],
      recommendedStage: 'screening',
      analyzedAt: daysAgo(7),
    },
  },
];

export const mockActivities: ActivityItem[] = [
  { id: 'a1', type: 'upload', candidateId: '11', candidateName: 'Reem Abdullah', description: 'CV uploaded for Full Stack Developer position', timestamp: hoursAgo(1) },
  { id: 'a2', type: 'upload', candidateId: '7', candidateName: 'Nora Al-Qahtani', description: 'CV uploaded for Data Scientist position', timestamp: hoursAgo(3) },
  { id: 'a3', type: 'report_generated', candidateId: '6', candidateName: 'Khalid Al-Dosari', description: 'AI analysis completed — Score: 71/100', timestamp: hoursAgo(6) },
  { id: 'a4', type: 'stage_change', candidateId: '1', candidateName: 'Sarah Al-Rashid', description: 'Moved to Onboarding stage', timestamp: daysAgo(1) },
  { id: 'a5', type: 'offer_sent', candidateId: '9', candidateName: 'Aisha Malik', description: 'Offer accepted — Starting March 15', timestamp: daysAgo(2) },
  { id: 'a6', type: 'stage_change', candidateId: '8', candidateName: 'Youssef Ibrahim', description: 'Offer sent — Awaiting response', timestamp: daysAgo(3) },
  { id: 'a7', type: 'note_added', candidateId: '4', candidateName: 'Ahmed bin Nasser', description: 'CTO added note: Impressive Kubernetes expertise', timestamp: daysAgo(5) },
  { id: 'a8', type: 'stage_change', candidateId: '4', candidateName: 'Ahmed bin Nasser', description: 'Moved to CEO Interview stage', timestamp: daysAgo(5) },
];
